package app.loveplusone;

import android.app.Notification;
import android.os.Build;

import androidx.annotation.NonNull;

import com.google.androidbrowserhelper.playbilling.digitalgoods.DigitalGoodsRequestHandler;

/**
 * The service Chrome hands a notification to, so the app posts it rather than
 * the browser.
 *
 * Bubblewrap generates this class and it is regenerated by `bubblewrap update`,
 * so the override below has to be re-applied after one — there is a test in
 * apps/android/twa.test.ts that fails if it goes missing.
 *
 * ── why the origin is stripped ──────────────────────────────────────────────
 *
 * Chrome builds every web notification with the origin in `subText`, and that
 * survives delegation: a member's lock screen read
 *
 *     ⁺One · www.loveplusone.app
 *     Someone sent you a message
 *
 * The wordmark is deliberately non-obvious and the domain is not — "One" tells
 * a passer-by nothing, "loveplusone.app" tells them it is a dating app. On an
 * app whose whole premise is that disclosure is the member's to make, that is
 * the wrong half to print.
 *
 * It is not spoofing: the notification is posted BY this app, ABOUT this app's
 * own origin, and the app's name and icon are the attribution. Chrome adds the
 * origin because a browser showing notifications for arbitrary sites has to;
 * that reasoning does not survive the notification becoming ours.
 *
 * ── it must never lose a notification ───────────────────────────────────────
 *
 * Wrapped, and falls back to the untouched notification on any failure.
 * `recoverBuilder` reads back a Notification that Chrome built, and a build it
 * cannot reconstruct would otherwise throw inside the delegation path — where
 * the failure is silence, which is exactly the class of bug this whole area
 * has already produced twice.
 */
public class DelegationService extends
        com.google.androidbrowserhelper.trusted.DelegationService {

    @Override
    public void onCreate() {
        super.onCreate();

        registerExtraCommandHandler(new DigitalGoodsRequestHandler(getApplicationContext()));
    }

    @Override
    public boolean onNotifyNotificationWithChannel(
            @NonNull String platformTag,
            int platformId,
            @NonNull Notification notification,
            @NonNull String channelName) {

        Notification toPost = notification;

        // recoverBuilder is API 24+. minSdk here is 23, so the guard is real
        // rather than defensive — on 23 the origin stays and nothing breaks.
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.N) {
            try {
                toPost = Notification.Builder
                        .recoverBuilder(getApplicationContext(), notification)
                        .setSubText(null)
                        .build();
            } catch (Throwable ignored) {
                // Post what Chrome built. An origin on the lock screen is worse
                // than the app's own name; no notification at all is worse than
                // both.
                toPost = notification;
            }
        }

        return super.onNotifyNotificationWithChannel(platformTag, platformId, toPost, channelName);
    }
}
