import { readFileSync } from "node:fs";

import { describe, expect, it } from "vitest";

import fixture from "./app-store-jws.fixture.json";
import { JwsError } from "./app-store-jws";
import { statusFromNotification, verifyAppStoreNotification } from "./app-store-notifications";

/**
 * Everything that happens to a subscription after the purchase happens with
 * nobody in the app: a renewal, a card that fails, a refund granted by Apple
 * Support, a cancellation from Settings. So these tests are about the cases a
 * device would never report — and about the two that a date comparison alone
 * gets wrong in opposite directions.
 *
 * Fixtures are envelopes generated by scripts/make-appstore-fixture.mjs, each
 * carrying its own signed transaction, so the nesting is real rather than
 * simulated.
 */
const at = { now: fixture.now, rootPem: fixture.testRootPem };
const N = fixture.notifications;
const read = (jws: string) => verifyAppStoreNotification(jws, at);
const statusOf = (jws: string) => statusFromNotification(read(jws), fixture.now);

describe("verifying a notification", () => {
  it("reads the type, subtype and the transaction nested inside", () => {
    const n = read(N.gracePeriod);
    expect(n.type).toBe("DID_FAIL_TO_RENEW");
    expect(n.subtype).toBe("GRACE_PERIOD");
    expect(n.environment).toBe("Sandbox");
    expect(n.transaction?.originalTransactionId).toBe("2000000800000001");
  });

  it("refuses a genuine envelope wrapping a forged transaction", () => {
    // The envelope verifying says nothing about a payload nested inside it, and
    // this is the shape of the mistake: verify the outer JWS, then read the
    // inner one as data because it arrived inside something trusted.
    expect(() => read(N.forgedInner)).toThrow(JwsError);
    expect(() => read(N.forgedInner)).toThrow(/does not end at Apple's root/);
  });

  it("refuses a notification about another app", () => {
    // bundleId sits at data.bundleId here, not at the top level — which is why
    // the signature check had to be split from the transaction check.
    expect(() => read(N.otherBundle)).toThrow(/notification is for com.someone.else/);
  });

  it("accepts TEST, which carries no data at all", () => {
    // App Store Connect's "send test notification" button is how anybody first
    // confirms the URL is wired. Rejecting it for having no bundleId makes the
    // one diagnostic Apple offers report a failure.
    const n = read(N.test);
    expect(n.type).toBe("TEST");
    expect(n.transaction).toBeUndefined();
    expect(statusFromNotification(n, fixture.now)).toBeNull();
  });
});

describe("what a notification changes", () => {
  it("keeps a member in service while Apple retries their card", () => {
    // THE case for the `grace` status existing. The transaction still carries
    // the old, passed expiry, so reading dates alone would lock somebody out
    // over a payment their bank re-authorises an hour later.
    expect(statusOf(N.gracePeriod)).toBe("grace");
    expect(read(N.gracePeriod).transaction!.expiresDate).toBeLessThan(fixture.now);
  });

  it("does not, when there is no grace period", () => {
    expect(statusOf(N.failedNoGrace)).toBe("expired");
  });

  it("ends access on a refund with weeks still on the clock", () => {
    // The other direction, and the one iap_entitlements was shaped around: a
    // refund revokes NOW and leaves expiresDate months out.
    expect(read(N.refund).transaction!.expiresDate).toBeGreaterThan(fixture.now);
    expect(statusOf(N.refund)).toBe("revoked");
    expect(statusOf(N.revoke)).toBe("revoked");
  });

  it("takes a renewal's new expiry from the transaction", () => {
    expect(statusOf(N.didRenew)).toBe("active");
    expect(statusOf(N.subscribed)).toBe("active");
  });

  it("expires when Apple says the term or the grace period is over", () => {
    expect(statusOf(N.expired)).toBe("expired");
    expect(statusOf(N.gracePeriodExpired)).toBe("expired");
  });

  it("changes nothing when auto-renew is switched off", () => {
    // Not a cancellation. They keep what they paid for until it runs out, and
    // treating this as a loss of access takes away a month somebody has bought.
    expect(statusOf(N.renewalStatusChanged)).toBeNull();
    expect(statusOf(N.priceIncrease)).toBeNull();
  });
});

/**
 * The route is a handler, so what can be checked without a request context is
 * that the three decisions it must not get wrong are still written down.
 */
describe("the notification route", () => {
  const source = readFileSync(
    new URL("../app/api/app-store/notifications/route.ts", import.meta.url),
    "utf8",
  );

  it("updates and never inserts", () => {
    // A notification identifies a subscription, not a member — it carries no
    // appAccountToken on every type. Creating a row here would mean inventing
    // the binding that the schema's unique key and trigger exist to protect.
    expect(source).toMatch(/\.update\(/);
    expect(source).not.toMatch(/\.(insert|upsert)\(/);
  });

  it("refuses a body it cannot verify rather than acknowledging it", () => {
    // There is no shared secret here. The signature IS the authentication, so
    // an unverifiable body is a stranger claiming somebody renewed.
    expect(source).toMatch(/status: 400/);
    expect(source).toMatch(/"unverified"/);
  });

  it("retries only the failure worth retrying", () => {
    // A write that failed is genuine news we could not record — worth a 500 so
    // Apple sends it again. A type we have no opinion about is acknowledged, or
    // Apple retries it for days.
    expect(source).toMatch(/status: 500/);
    expect(source).toMatch(/applied: false/);
  });

  it("logs a type and a count, never a transaction id", () => {
    // §9.6 — a transaction id is an identifier.
    expect(source).not.toMatch(/console\.\w+\([^)]*transaction\.originalTransactionId/);
    expect(source).toMatch(/rows: data\?\.length/);
  });
});
