import { X509Certificate } from "node:crypto";
import { readFileSync } from "node:fs";

import { describe, expect, it } from "vitest";

import fixture from "./app-store-jws.fixture.json";
import { SOURCE_ROOT, filesMatching } from "./source-scan";
import {
  APPLE_ROOT_CA_G3_SHA256,
  JwsError,
  entitlementStatusOf,
  verifyAppStoreJws,
  type AppStoreTransaction,
} from "./app-store-jws";

/**
 * This function is the whole of the fraud check on the iOS purchase path.
 *
 * Everything else in the flow is bookkeeping. A member's device says "I bought
 * this", and the only reason that is not simply believed is that the claim
 * carries a signature chaining to Apple's root. So the tests worth having are
 * the ones that try to get a grant without one.
 *
 * The fixtures are a chain generated by scripts/make-appstore-fixture.mjs, not
 * Apple's — a chain ending at Apple's root can only be produced by Apple, which
 * is the point of it. The happy path therefore passes that root in explicitly,
 * and the FIRST test below is the one that keeps that honest: the default
 * anchor is Apple Root CA - G3, by fingerprint. Without it a test root could
 * quietly become the production one and every other test here would still pass.
 */
const at = { now: fixture.now, rootPem: fixture.testRootPem };
const good = (jws: string): AppStoreTransaction => verifyAppStoreJws(jws, at);

describe("the anchor", () => {
  it("defaults to Apple Root CA - G3 and not to anything a test supplied", async () => {
    const { APPLE_ROOT_CA_G3_SHA256: pinned } = await import("./app-store-jws");
    expect(pinned).toBe(APPLE_ROOT_CA_G3_SHA256);

    // The constant and the embedded PEM have to be the same certificate, or the
    // pin describes a certificate nothing uses. Read the PEM back out of the
    // module source rather than trusting that they were kept in step.
    const source = readFileSync(new URL("./app-store-jws.ts", import.meta.url), "utf8");
    const pem = /-----BEGIN CERTIFICATE-----[\s\S]+?-----END CERTIFICATE-----/.exec(source)?.[0];
    expect(pem).toBeTruthy();
    const cert = new X509Certificate(pem!);
    expect(cert.fingerprint256).toBe(APPLE_ROOT_CA_G3_SHA256);
    expect(cert.subject).toContain("Apple Root CA - G3");
    // Self-signed: a root is its own issuer, and one that is not is not a root.
    expect(cert.issuer).toBe(cert.subject);
  });

  it("rejects a chain anchored anywhere else, however well-formed", () => {
    // The forgery. Its own root, its own leaf, every signature inside it
    // verifying perfectly — which is precisely why checking signatures without
    // checking the anchor proves nothing at all.
    expect(() => good(fixture.forged)).toThrow(JwsError);
    expect(() => good(fixture.forged)).toThrow(/does not end at Apple's root/);
  });

  it("rejects the real chain when the bytes were signed by another key", () => {
    // Chain says Apple, signature says somebody else. Catching this is the leaf
    // key check rather than the anchor check, and both have to be present.
    expect(() => good(fixture.wrongSigner)).toThrow(/signature does not verify/);
  });
});

describe("the header", () => {
  it("refuses alg: none", () => {
    // The oldest JWT attack there is: drop the signature, say none, and hope
    // the verifier does as it is told.
    expect(() => good(fixture.algNone)).toThrow(/unexpected alg none/);
  });

  it("refuses anything that is not a compact JWS", () => {
    for (const bad of ["", "a.b", "a.b.c.d", "not-a-jws"]) {
      expect(() => good(bad)).toThrow(JwsError);
    }
  });

  it("refuses a header with no chain at all", () => {
    const [, payload, signature] = fixture.valid.split(".");
    const header = Buffer.from(JSON.stringify({ alg: "ES256" })).toString("base64url");
    expect(() => good(`${header}.${payload}.${signature}`)).toThrow(/no certificate chain/);
  });
});

describe("a verified transaction", () => {
  it("comes back with the fields the entitlement is built from", () => {
    const t = good(fixture.valid);
    expect(t.originalTransactionId).toBe("2000000800000001");
    expect(t.productId).toBe("3months");
    expect(t.bundleId).toBe("app.loveplusone");
    expect(t.appAccountToken).toBe(fixture.member);
    // Milliseconds, which is Apple's choice and not the seconds a JWT uses.
    // apns.test.ts pins the same trap from the other direction.
    expect(t.expiresDate).toBeGreaterThan(fixture.now);
    expect(String(t.expiresDate)).toHaveLength(13);
  });

  it("carries revocation and expiry through untouched", () => {
    expect(good(fixture.revoked).revocationDate).toBeLessThan(fixture.now);
    expect(good(fixture.expired).expiresDate).toBeLessThan(fixture.now);
    // Neither is rejected here. Whether they GRANT anything is the caller's
    // question, and answering it here would make an expired receipt
    // indistinguishable from a forged one.
    expect(good(fixture.revoked).productId).toBe("3months");
  });

  it("keeps the product id Apple sent rather than one derived from a plan", () => {
    expect(good(fixture.sixMonths).productId).toBe("6months");
  });
});

describe("a transaction that is signed but not ours", () => {
  it("is refused when it belongs to another app", () => {
    // Apple's root anchors every app on the store. Without this check, a
    // transaction bought in somebody else's app is a validly signed statement
    // that somebody paid — just not us.
    expect(() => good(fixture.otherBundle)).toThrow(/transaction is for com.someone.else/);
  });

  it("is refused when a certificate is out of date", () => {
    // A chain that was fine yesterday. `now` is what makes this testable at
    // all, and what stops the suite failing on a calendar.
    const longAfter = Date.parse("2200-01-01T00:00:00Z");
    expect(() => verifyAppStoreJws(fixture.valid, { ...at, now: longAfter })).toThrow(
      /not valid at this time/,
    );
  });
});

describe("what a transaction entitles", () => {
  const now = fixture.now;
  const base = {
    transactionId: "t",
    originalTransactionId: "o",
    bundleId: "b",
    productId: "p",
    purchaseDate: 0,
  };

  it("grants while it is unexpired", () => {
    expect(entitlementStatusOf({ ...base, expiresDate: now + 1000 }, now)).toBe("active");
  });

  it("stops granting the moment it expires", () => {
    expect(entitlementStatusOf({ ...base, expiresDate: now }, now)).toBe("expired");
    expect(entitlementStatusOf({ ...base, expiresDate: now - 1 }, now)).toBe("expired");
  });

  it("treats a transaction with no expiry as spent rather than eternal", () => {
    // A subscription always has one. Something without an expiry is a
    // non-renewing product or a payload we do not understand, and the schema
    // refuses to store a granting row with a null expiry anyway — so the only
    // two consistent answers are "expired" and "refuse", and this is the one
    // that does not lose the row.
    expect(entitlementStatusOf(base, now)).toBe("expired");
  });

  it("puts revocation ahead of the clock, which is the whole point", () => {
    // A refund revokes access NOW and leaves expiresDate months out. Checking
    // the clock first keeps a refunded member premium for the rest of a term
    // they no longer paid for, and nothing about the row would look wrong.
    expect(
      entitlementStatusOf(
        { ...base, expiresDate: now + 90 * 86_400_000, revocationDate: now - 1 },
        now,
      ),
    ).toBe("revoked");
  });
});

/**
 * The action itself is a `"use server"` module: it cannot be imported into a
 * test without a Next request context, and every export in it must be async, so
 * there is nothing pure left to call. What can be checked is that the four
 * decisions it must not get wrong are still written the way they were reasoned
 * about — each of them is a one-line edit away from being silently wrong.
 */
describe("the purchase action", () => {
  const source = readFileSync(
    new URL("../app/app/settings/premium/iap-actions.ts", import.meta.url),
    "utf8",
  );
  const migration = readFileSync(
    new URL(
      "../../../../supabase/migrations/20260826000400_a_purchase_is_recorded_once.sql",
      import.meta.url,
    ),
    "utf8",
  );

  it("writes with the service role rather than the member's session", () => {
    // iap_entitlements grants members SELECT and nothing else. A member able to
    // write their own entitlement makes every other check decorative.
    expect(source).toMatch(/serviceClient\(\)\.rpc\("record_iap_entitlement"/);
  });

  it("goes through the RPC rather than an upsert", () => {
    // PostgREST builds `on conflict do update set` from every column in the
    // payload, and the payload must carry user_id for the INSERT — so an upsert
    // proposes to rebind the row on every replay, and replay is the normal case
    // because StoreKit redelivers until a transaction is finished.
    expect(source).not.toMatch(/\.upsert\(/);
    expect(source).not.toMatch(/onConflict/);
  });

  it("never updates the member a subscription belongs to", () => {
    // The property, read out of the SQL rather than inferred from the client
    // call. Everything between `do update set` and the `where` is what a replay
    // is allowed to change.
    //
    // Comments stripped first, and not as a precaution: this file explains the
    // very statement being searched for, so the first version of this test
    // matched the phrase `do update set` inside the paragraph describing it and
    // read a prose sentence as the update list. Exactly what
    // scripts/declared-objects.mjs had to learn about `constraint <name>`.
    const sql = migration.replace(/--[^\n]*/g, "");
    const setList = /do update\s+set([\s\S]*?)\s+where/i.exec(sql)?.[1] ?? "";
    expect(setList).toBeTruthy();
    expect(setList).toMatch(/status\s*=/);
    expect(setList).toMatch(/expires_at\s*=/);
    expect(setList).not.toMatch(/\buser_id\s*=/);
    // And a row belonging to somebody else is skipped rather than raised on: an
    // exception on the path of somebody who has just paid is a 500 and an
    // unfinished transaction.
    expect(sql).toMatch(/where\s+public\.iap_entitlements\.user_id\s*=\s*p_user_id/i);
  });

  it("keeps the RPC away from members", () => {
    // A client that can call it can write its own entitlement.
    expect(migration).toMatch(/revoke all on function[\s\S]*?from public, anon, authenticated/i);
  });

  it("takes the expiry from Apple's payload and never from a clock", () => {
    // A replayed transaction must not extend anybody's subscription. Same rule
    // the Stripe webhook follows with current_period_end.
    expect(source).toMatch(/p_expires_at: transaction\.expiresDate/);
    expect(source).not.toMatch(/p_expires_at:[^,]*Date\.now\(\)/);
  });

  it("compares the account token case-insensitively at both ends", () => {
    // Apple does not promise the case it round-trips a UUID in; ours are stored
    // lowercase. A case-sensitive compare fails every real purchase and no
    // fraudulent one — which is a bug that looks like fraud detection working.
    expect(source).toMatch(/token\.toLowerCase\(\) !== auth\.user\.id\.toLowerCase\(\)/);
  });

  it("refuses a transaction that names nobody", () => {
    expect(source).toMatch(/if \(!token\) return \{ ok: false, reason: "unbound" \}/);
  });

  it("tells a second account it is not theirs rather than that it failed", () => {
    // One Apple ID, two Plus One accounts, a restore on the second. An honest
    // mistake, and "retry" is the wrong thing to offer for it.
    expect(source).toMatch(/recorded === null/);
    expect(source).toMatch(/reason: "not_yours"/);
  });

  it("logs a reason and never the receipt", () => {
    // §9.6. A rejected JWS is still a receipt, and a transaction id is an
    // identifier.
    expect(source).not.toMatch(/console\.(error|info|log)\([^)]*jws/);
  });
});

/**
 * The sweep, rather than another assertion about one file.
 *
 * Every source-reading test above pins the shape of a line in a file it was
 * pointed at, and 2ab1de0 showed what that cannot see: a second implementation
 * somewhere else. These are the two properties in this area where a rival would
 * be a hole rather than an untidiness, asked of the whole tree.
 */
const read = (path: string) => readFileSync(path, "utf8");

describe("no rival can undo what these files promise", () => {
  it("keeps every binding to a member behind the one RPC", () => {
    // record_iap_entitlement is what makes a purchase belong to one member and
    // stay there: its update list has no user_id, so a replay moves the term
    // and not the owner. An INSERT or UPSERT anywhere else is a second way to
    // create that binding, and PostgREST's upsert writes every column it is
    // given — which is precisely how the first version of this got it wrong.
    //
    // The notification route's UPDATE is fine and deliberately not matched: it
    // can change a term, never create a row, so there is nobody it could bind.
    const offenders = filesMatching(
      /from\(["']iap_entitlements["']\)[\s\S]{0,400}?\.(insert|upsert)\(/,
      ["lib/app-store-jws.test.ts"],
      read,
    );
    expect(offenders, `a second way to bind a purchase: ${offenders.join(", ")}`).toEqual([]);
  });

  it("never verifies a signature without also checking whose app it is", () => {
    // `verifyAppleJws` deliberately answers only "did Apple sign this". Apple's
    // root anchors EVERY app on the store, so a transaction bought in somebody
    // else's app is just as validly signed as one bought in ours — the identity
    // check is what makes the signature mean anything here.
    //
    // Its docblock says each caller checks its own fields, and until now
    // nothing held anyone to that. A third caller that verified and read the
    // payload would be a hole with a green test suite above it.
    const callers = filesMatching(/verifyAppleJws</, ["lib/app-store-jws.ts"], read);
    const unchecked = callers.filter((path) => !/bundleId/.test(read(`${SOURCE_ROOT}/${path}`)));
    expect(unchecked, `verifies without checking the bundle: ${unchecked.join(", ")}`).toEqual([]);
    // And the sweep only means something if it is finding the callers at all.
    expect(callers).toContain("lib/app-store-notifications.ts");
  });
});
